name: Deploy Dev

on:
  push:
    branches: [dev]

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Run deployment script
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} 'bash /var/www/archeage-tracker/dev/deploy.sh'
